### ISSUE TITLE
Diagrama de Classe - Players

### ISSUE THREAD

**Issue by KerenMoreno** [Professor-Dudarts/ludus_service_players#23]

**Comment by KerenMoreno** [comment]
Participantes

- [x] Responsáveis: @Dierison e @GustavoWalker 
- [x] Revisor: @AntonioUHT73404

**Comment by GustavoWalker** [comment]
Segue anexo início do diagrama de classe:
[diagramaClasse.zip](https://github.com/Professor-Dudarts/ludus_service_players/files/10984717/diagramaClasse.zip)

**Comment by Dierison** [comment]
Eu terminei o diagrama de classe, por favor revisar e avisar caso precise de alguma mudança.
[diagramaClasse1.zip](https://github.com/Professor-Dudarts/ludus_service_players/files/11009249/diagramaClasse1.zip)

**Comment by AntonioUHT73404** [comment]
O diagrama esta em conformidade com os requisitos levantados para o projeto.

**Comment by GustavoWalker** [comment]
![Image](https://user-images.githubusercontent.com/44181021/226469584-e0fc8fe8-5477-4f67-8f0b-a87aa0eb6da3.png)

**Comment by Dierison** [comment]
![Image](https://user-images.githubusercontent.com/62193598/227380420-8bfcd367-8723-4811-8fec-df9de63bb831.png)

Diagrama atualizado.
